---
    environment: production
    chdir: /home/sunny/orouxgami.rousseur.org
    address: 127.0.0.1
    user: www-data
    group: www-data
    port: 4667
    pid: /home/sunny/orouxgami.rousseur.org/thin.pid
    rackup: /home/sunny/orouxgami.rousseur.org/config.ru
    log: /home/sunny/orouxgami.rousseur.org/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

